// action types for user sign-up process
export const UPDATE_SIGNUP_INPUT = "UPDATE_USER_INPUT";
export const USER_REGISTER_START = "USER_REGISTER_START";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const SET_TOKEN = "SET_TOKEN";
export const SET_USER = "SET_USER";

// action type for user sign-in process
export const UPDATE_SIGNIN_INPUT = "UPDATE_SIGNIN_INPUT";
export const USER_SIGNIN_START = "USER_SIGNIN_START";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

// action types for getting seeded recipes
export const GET_SEEDED_RECIPES_START = "GET_SEEDED_RECIPES_START";
export const GET_SEEDED_RECIPES_SUCCESS = "GET_SEEDED_RECIPES_SUCCESS";
export const GET_SEEDED_RECIPES_FAIL = "GET_SEEDED_RECIPES_FAIL";

// action types for getting user recipes
export const GET_USER_RECIPES_START = "GET_USER_RECIPES";
export const GET_USER_RECIPES_SUCCESS = "GET_USER_RECIPES_SUCCESS";
export const GET_USER_RECIPES_FAIL = "GET_USER_RECIPES_FAIL";
export const SET_RECIPE_TO_EDIT = "SET_RECIPE_TO_EDIT";

// action types for getting ingredients
export const GET_INGREDIENTS_START = "GET_INGREDIENTS_START";
export const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_FAIL = "GET_INGREDIENTS_FAIL";

// action types for getting ingredients
export const GOOGLE_SIGNIN_START = "GOOGLE_SIGNIN_START";
export const GOOGLE_SIGNIN_SUCCESS = "GOOGLE_SIGNIN_SUCCESS";
export const GOOGLE_SIGNIN_FAIL = "GOOGLE_SIGNIN_FAIL";

// action type for user logging out
export const USER_LOGOUT = "USER_LOGOUT";

// action stypes for  user recipe CRUD
export const DELETE_USER_RECIPE_START = "DELETE_USER_RECIPE_START";
export const DELETE_USER_RECIPE_SUCCESS = "DELETE_USER_RECIPE_SUCCESS";
export const DELETE_USER_RECIPE_FAIL = "DELETE_USER_RECIPE_FAIL";
export const UPDATE_USER_RECIPE_INPUT = "UPDATE_USER_RECIPE_INPUT";
export const UPDATE_USER_RECIPE_START = "UPDATE_USER_RECIPE_START";
export const UPDATE_USER_RECIPE_SUCCESS = "UPDATE_USER_RECIPE_SUCCESS";
export const UPDATE_USER_RECIPE_FAIL = "UPDATE_USER_RECIPE_FAIL";
export const NEW_RECIPE_INPUT_UPDATE = "NEW_USER_INPUT_UPDATE";
export const CREATE_USER_RECIPE_START = "CREATE_USER_RECIPE_START";
export const CREATE_USER_RECIPE_SUCCESS = "CREATE_USER_RECIPE_SUCCESS";
export const CREATE_USER_RECIPE_FAIL = "CREATE_USER_RECIPE_FAIL";